name: Greetings on new PR and issues

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for bringing this to our notice!'
        pr-message: 'Hey, Thanks for the pull request. We will be assigning someone to review it shortly.'
